### ISSUE TITLE
Formatting YARA Files in Bulk

### ISSUE THREAD

**Issue by xorhex** [avast/yls#74]
Using either the command line or a custom python script, is it possible to pass in a yara rule to yls and have the formatted version returned?  Hoping to use this to format some yara rules in bulk.  If yes, pointers on where to look?  Thanks!

**Comment by MatejKastak** [comment]
Hi xorhex!

Something like that is possible, for sure :) YLS uses [Yaramod](https://github.com/avast/yaramod) to do the formatting. And you can use it also from your scripts.

Here is a quick example script that formats the YARA file specified as the first argument:
```python
#!/usr/bin/env python3

import sys
import yaramod

ymod = yaramod.Yaramod()

yfile = ymod.parse_file(sys.argv[1])
print(yfile.text_formatted)
```

[Here](https://yaramod.readthedocs.io/en/latest/formatting_rulesets.html) is some more related documentation.

**Comment by xorhex** [comment]
This is awesome, thank you!

**Comment by MatejKastak** [comment]
I am glad I could help :slightly_smiling_face: , if you have any other questions feel free to open new issues. Closing this issue now.
